### ISSUE TITLE
ipython_directive and sphinx_copybutton extensions are broken

### ISSUE THREAD

**Issue by djhoese** [NSLS-II/scientific-python-cookiecutter#35] opened 2018-08-13 15:21 UTC
I know this isn't this projects responsibility, but since these extensions are included by default I thought I'd point out that neither of these extensions worked for me. I changed my travis environment to install ipython, sphinx, and sphinx_rtd_theme from conda. "sphinx-copybutton" was installed with pip. The ipython directive extension had an import error: `ImportError: cannot import name 'Directive'` and I noticed it discussed [here](https://github.com/pandas-dev/pandas/issues/20955).

The copybutton extension resulted in `has no setup() function; is it really a Sphinx extension module?`. Has anyone else run in to these issues?

**Comment by danielballan** [comment] 2018-08-14 15:05
Thanks for the heads up. I encountered the `sphinx-copybutton` as well and [submitted a fix](https://github.com/choldgraf/sphinx-copybutton/pull/3).

I cannot reproduce the ipython directive issue. Can you post what versions of sphinx, IPython, and numpydoc you are using?

**Comment by djhoese** [comment] 2018-08-14 15:10
So, as usual, the bug has magically disappeared. It seems to build find for me now. I'll try reenabling both extensions when your PR is merged and see if travis can build it properly.

**Comment by danielballan** [comment] 2018-08-14 15:45
The fix is merged and [the master branch passes again](https://travis-ci.org/NSLS-II/scientific-python-cookiecutter/builds/415947023). I'll leave this issue open until you verify that it works for you as well.

**Comment by danielballan** [comment] 2018-08-20 13:49
Assuming as is well. Please reopen if there is still a problem. Thanks again for flagging this. :- )

**Closed by danielballan** 2018-08-20 13:49 UTC

**Comment by djhoese** [comment] 2018-08-20 14:31
Seems to build fine now. Thanks!

https://travis-ci.org/geoxarray/geoxarray/builds/418255106
